PL_TORCH_DISTRIBUTED_BACKEND=nccl \
/scratch/sz9jt/.conda/envs/medicaldiffusion/bin/python train_vqgan.py \
dataset=combined_brain_17mm \
dataset.root_dir=/home/sz9jt/data/t1w_processed/outputs/ \
model=vq_gan_3d \
model.gpus=4 \
model.precision=16-mixed \
model.embedding_dim=6 \
model.n_hiddens=16 \
model.downsample=[4,4,4] \
model.num_workers=2 \
model.gradient_clip_val=1.0 \
model.lr=3e-4 \
model.discriminator_iter_start=10000 \
model.perceptual_weight=4 \
model.image_gan_weight=1 \
model.video_gan_weight=1 \
model.gan_feat_weight=4 \
model.batch_size=5 \
model.n_codes=16384 \
model.accumulate_grad_batches=1 